# Generated by Django 4.1.13 on 2023-11-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fact', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image_urls', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'animals',
            },
        ),
    ]
